#!/bin/bash

# stop on any unhandled error
set -e

# @TODO: pipefail not in POSIX
set -o pipefail

# show commands (debug)
#set -x

# shellcheck source=src/container/output.inc.sh
source "/output.inc.sh"

# @TODO: Nag if remote git branches for debian/upstream/pristine-tar have newer stuff than locally (risk for new local changes to be in vain)

# @TODO: Nag if git tags are missing for past debian/changelog releases (i.e. forgot to run 'gbp tag')

# @TODO: Nag if local git tags have not been pushed (i.e. forgot to run 'gbp push')

# @TODO: find * -type f | xargs spellintian --picky
# @TODO: enchant-2 -d en -a debian/changelog # ispell line format, does not work for a human
# @TODO: aspell -d en -c debian/changelog # interactive mode, checks whole file not just latest entry
# @TODO: aspell --mode=debctrl -c debian/control
# @TODO: find -name *.md -exec aspell --mode=markdown -c "{}" +;
# @TODO: hunspell -d en_US debian/changelog # interactive mode

# @TODO: For each manpage run: LC_ALL=C.UTF-8 MANROFFSEQ='' MANWIDTH=80 man --warnings -E UTF-8 -l -Tutf8 -Z $MANPAGE >/dev/null

# @TODO: suspicious-source --verbose --directory . # no output if no findings, and most findings false positives

# @TODO: 'duck -v --color=always' check validity or URLS in debian/control, debian/upstream, debian/copyright etc

# @TODO: adequate # Findings for listdc++6 and libc6 out-of-the-box, but could
# be useful if current package installed and added to
# '/var/lib/adequate/pending' for limiting checks to it

# @TODO: find . -type f \( -iname '*.po' -o -iname '*.pot' -o -iname '*.mo' -o -iname '*.gmo' \) -exec i18nspector --jobs 1 {} +
# @TODO: find . -type f \( -iname '*.po' -o -iname '*.pot' \) -exec msgfmt --check --check-compatibility --check-accelerators --output-file=/dev/null {} \;

# @TODO: find . -type f \( -iname '*.yaml' -o -iname '*.yml' -o -iwholename ./debian/upstream/metadata -o -iwholename ./debian/upstream/edam \) -exec yamllint {} +

# @TODO: blhc --all --debian --line-numbers --color *.build
# or alternatively as Salsa-CI uses: blhc --debian --line-numbers --color ${SALSA_CI_BLHC_ARGS} ${WORKING_DIR}/*.build || [ $? -eq 1 ]
# However both versions result in blhc outputting 'No compiler commands' so I am not sure if it works at all?

# @TODO: diffoscope --html report.html old.deb new.deb

# Lintian brush needs to run first as it refuses to run if there are any
# uncommitted changes, potentially introduced by the other tools
log_info "Run all tools that may help improve the Debian packaging in an automated fashion"

# Read shell scripts into arrays (empty if no matches)
mapfile -t SH_SCRIPTS < <(grep -rlnw debian/ -e '^#!.*/sh' | sort -u || true)
mapfile -t BASH_SCRIPTS < <(grep -rlnw debian/ -e '^#!.*/bash' | sort -u || true)

# Echo all commands so it is easy for users to re-run them manually
set -x

# Disable until lintian-brush re-enters Debian testing (and Ubuntu 26.04), see
# https://tracker.debian.org/pkg/lintian-brush
#lintian-brush --no-update-changelog --modern --uncertain

# Don't stop on errors as the tools below are likely to emit exit codes if they
# have findings but Debcraft should continue to execute and run all of them
set +e

codespell --write-changes --check-filenames --check-hidden \
  --skip="debian/changelog,debian/patches,debian/vendor,debian/source/lintian-overrides,*.lintian-overrides,*.po,*.pot" \
  debian/
# add overrides in debian/.codespellrc

debputy lint --spellcheck --auto-fix

# Apply `debputy reformat --style black`
debputy reformat --style black

# Apply `wrap-and-sort -vast` that modifies more files than debputy, and helps
# ensure all changes are easy to track in git
wrap-and-sort -vast

lrc
# add overrides in debian/lrc.config

set +x

# Run Shellcheck only if files of the type were found
if [ "${#SH_SCRIPTS[@]}" -gt 0 ]
then
  shellcheck -x --enable=all --shell=sh "${SH_SCRIPTS[@]}"
  shellcheck -x --enable=all --format=diff --shell=sh "${SH_SCRIPTS[@]}" >> shellcheck-fixes.diff
fi

if [ "${#BASH_SCRIPTS[@]}" -gt 0 ]
then
  shellcheck -x --enable=all --shell=bash "${BASH_SCRIPTS[@]}"
  shellcheck -x --enable=all --format=diff --shell=bash "${BASH_SCRIPTS[@]}" >> shellcheck-fixes.diff
fi

# Apply patch if not empty, otherwise just remove it
if [[ -s shellcheck-fixes.diff ]]
then
  patch --strip=1 < shellcheck-fixes.diff
else
  rm -f shellcheck-fixes.diff
fi

# Remove extra file generated by one of the tools above
rm -f .config/breezy/ignore || true


# Stop improvements here if the source package directory isn't tracked in git
if ! git rev-parse --git-dir >/dev/null 2>&1
then
  exit 0
fi

# Automatically make specific changes and commit them in git

# Commit formatting changes if any files were modified by the tools above
if ! git diff --quiet
then
  git add -A
  git commit -F - <<'EOF'
Apply consistent formatting to packaging files

Run `debputy reformat --style black` and `wrap-and-sort -vast` to enforce
uniform deb822 formatting with one item per line. This makes future
changes to dependencies and other lists easier to track in git diffs.

No functional changes.
EOF
fi

# Drop redundant Rules-Requires-Root: no
if grep -qE "^\s*Rules-Requires-Root:\s*no\s*$" debian/control
then
  sed -i -E '/^\s*Rules-Requires-Root:\s*no\s*$/d' debian/control

  # Commit if file changed
  if ! git diff --quiet debian/control
  then
    git add debian/control
    git commit -F - <<'EOF'
Drop redundant `Rules-Requires-Root: no`

As of dpkg version 1.22.13, this field is set to "no" by default.
As such, in this case the Rules-Requires-Root field is redundant and should be
removed.
EOF
  fi
fi

# Debian Policy 4.7.3
if grep -qE "^\s*Priority:\s*optional\s*$" debian/control
then
  sed -i -E '/^\s*Priority:\s*optional\s*$/d' debian/control

  # Commit if file changed
  if ! git diff --quiet debian/control
  then
    git add debian/control
    git commit -F - <<'EOF'
Drop redundant `Priority: optional`

As of dpkg version 1.22.13, this field is set to "optional" by default.
As such, in this case the Priority field is redundant and should be
removed.
EOF
  fi
fi

# Bump Standards-Version to 4.7.3 (if not already)
if ! grep -qF "Standards-Version: 4.7.3" debian/control
then
  sed -i -E 's/^\s*Standards-Version:\s*.*\s*$/Standards-Version: 4.7.3/' debian/control

  # Commit if file changed
  if ! git diff --quiet debian/control
  then
    git add debian/control
    git commit -F - <<'EOF'
Bump Debian Policy version to 4.7.3

No changes required after reviewing checklist at
https://www.debian.org/doc/debian-policy/upgrading-checklist.html#version-4-7-3
EOF
  fi
fi

# -------------------------------------------------------------------------
# Auto‑bump copyright year in debian/copyright
# -------------------------------------------------------------------------

CURRENT_YEAR=$(date +%Y)

log_debug "Current year: $CURRENT_YEAR"

# If the current year already appears anywhere, nothing to do
if grep -qF "$CURRENT_YEAR" debian/copyright
then
  log_debug "Copyright year $CURRENT_YEAR already present in debian/copyright"
else
  # Find authors (name + email) who have committed to any file under debian/
  # in the previous calendar year
  SINCE_DATE=$((CURRENT_YEAR - 1))-01-01
  log_debug "Looking for commits since $SINCE_DATE"
  mapfile -t authors < <(
    git log --since="$SINCE_DATE" --format='%aN <%aE>' -- debian/ 2>/dev/null |
      sort -u
  )
  log_debug "Authors found: ${authors[*]}"

  if (( ${#authors[@]} ))
  then
    # Build an associative array mapping author → start year (first year seen)
    declare -A start_year
    for author in "${authors[@]}"
    do
      log_debug "Processing author: $author"
      # Look for an existing line for this author (any year, not just at line start)
      if line=$(grep -E "${author}" debian/copyright)
      then
        # Extract the earliest year mentioned for this author (first occurrence)
        yr=$(printf '%s' "$line" | grep -Eo '[0-9]{4}' | head -n1)
        start_year["$author"]=$yr
        log_debug "Existing entry found, start year = $yr"
      else
        start_year["$author"]=$CURRENT_YEAR
        log_debug "No existing entry, using current year = $CURRENT_YEAR"
      fi
    done

    # Write a temporary mapping file for awk (author<TAB>start_year)
    map_file="$(mktemp)"
    for a in "${!start_year[@]}"
    do
      printf '%s\t%s\n' "$a" "${start_year[$a]}" >> "$map_file"
    done
    log_debug "Start‑year map contents:"
    log_debug_var "$map_file"

    # Create a temporary file that will become the new copyright file
    tmp_file="$(mktemp)"

    log_debug "Starting AWK processing to detect Files: debian/* stanza"

    awk -v yr="$CURRENT_YEAR" -v hdr="Copyright:" -v map_file="$map_file" '
      BEGIN {
        # Load author → start_year mapping
        while ((getline line < map_file) > 0) {
          split(line, parts, "\t")
          author[parts[1]] = parts[2]
        }
        close(map_file)
        skip_authors = 0
        found_files = 0
        # print "AWK: Starting processing, map loaded with " length(author) " authors" > "/dev/stderr"
      }

      # Detect single-line format: Files: debian/*
      /^Files:[[:space:]]+debian\/\*[[:space:]]*$/ {
        # print "AWK: Found single-line Files: debian/* at line " NR > "/dev/stderr"
        print $0
        print hdr
        for (a in author) {
          start = author[a]
          if (start == yr) range = yr
          else range = start "-" yr
          print " " range " " a
        }
        skip_authors = 1
        found_files = 1
        next
      }

      # Detect multi-line format: Files:\n debian/*
      /^Files:[[:space:]]*$/ {
        # print "AWK: Found Files: header at line " NR ", checking next line" > "/dev/stderr"
        current_line = $0
        # Read the next line to check if it contains debian/*
        if ((getline next_line) > 0) {
          # print "AWK: Next line is: [" next_line "]" > "/dev/stderr"
          if (next_line ~ /^[[:space:]]+debian\/\*/) {
            # print "AWK: Found debian/* on continuation line - processing stanza" > "/dev/stderr"
            print current_line
            print next_line
            print hdr
            for (a in author) {
              start = author[a]
              if (start == yr) range = yr
              else range = start "-" yr
              print " " range " " a
            }
            skip_authors = 1
            found_files = 1
            next
          } else {
            # print "AWK: Next line does not contain debian/*, printing normally" > "/dev/stderr"
            print current_line
            print next_line
            next
          }
        } else {
          # End of file after Files: line
          print current_line
          next
        }
      }

      # While inside the author block, skip the original Copyright line
      # and any indented author lines
      skip_authors {
        if ($0 ~ /^Copyright:/) {
          # print "AWK: Skipping original Copyright line at " NR > "/dev/stderr"
          next
        }
        if ($0 ~ /^ /) {
          # print "AWK: Skipping indented author line at " NR > "/dev/stderr"
          next
        }
        # End of block when a non‑indented line that is not a Copyright appears
        # print "AWK: End of author block at line " NR ", resuming normal output" > "/dev/stderr"
        skip_authors = 0
      }

      # Default action: print the line
      {
        print $0
      }

      END {
        if (!found_files) {
          print "ERROR: Files: debian/* stanza not found in original file!" > "/dev/stderr"
        }
      }
    ' debian/copyright > "$tmp_file" && mv "$tmp_file" debian/copyright

    # Ensure the file ends with a newline (add one only if missing)
    if [ "$(tail -c1 debian/copyright | od -An -tx1 | tr -d ' \n')" != "0a" ]
    then
      echo "" >> debian/copyright
    fi

    # Clean up the temporary mapping file
    rm -f "$map_file"

    # Commit the updated copyright file
    git add debian/copyright
    git commit -F - <<'EOF'
Update copyright years for recent contributors

EOF
  else
    log_debug "No recent contributors found for debian/, no copyright update needed"
  fi
fi
