---
stages:
  - test
  - package

.test-prepare-container: &test-prepare-container |
  cd ${WORKING_DIR} # Don't repeat this step, it's just cd ./debian/output
  # Enable automatic restarts from maint scripts
  sed -i "s/101/0/g" -i /usr/sbin/policy-rc.d
  # Fake /sbin/runlevel to avoid warnings of "invoke-rc.d: could not determine current runlevel"
  echo -e '#!/bin/sh\necho "N 5"' > /sbin/runlevel; chmod +x /sbin/runlevel
  # Avoid the warnings of "debconf: unable to initialize frontend: Dialog"
  echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
  # Emit non-zero exit code also on warnings
  echo 'APT::Update::Error-Mode "any";' > /etc/apt/apt.conf.d/non-zero-exit-on-warnings
  # Prime the apt cache so later apt commands can run
  apt-get update -q

.test-enable-sid-repos: &test-enable-sid-repos
  - apt-get install -qq --yes --no-install-recommends ca-certificates curl
  # Replace any old repos with just Sid
  - echo 'deb http://deb.debian.org/debian sid main' > /etc/apt/sources.list
  # Upgrade minimal stack first
  - apt-get update -qq
  - curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/g/glibc/libc6_2.38-11_amd64.deb
  - curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/g/glibc/libc-bin_2.38-11_amd64.deb
  # Ensure upgrades past 2.38-11 are blocked so tests don't fail on usrmerge issues
  - apt-mark hold libc6 libc-bin
  - apt-get -q install --no-install-recommends --yes ./libc6_2.38-11_amd64.deb ./libc-bin_2.38-11_amd64.deb || export APT_STATUS="failed"
  # Due to https://bugs.debian.org/993755 and #975077 upgrades from Buster or
  # older to Bookworm or newer always fails on:
  #   /usr/bin/perl: error while loading shared libraries: libcrypt.so.1: cannot
  #     open shared object file: No such file or directory
  #   dpkg: error processing package libc6:amd64 (--configure):
  # Therefore, run this extra workaround if first run of apt-get install failed:
  - |
    if [ "$APT_STATUS" = "failed" ]
    then
      cd $(mktemp -d) # Use temp dir where apt can download and unpack files
      apt-get -y download libcrypt1
      dpkg-deb -x libcrypt1_*.deb .
      cp -ra usr/lib/* /lib/ || true # libcrypt 1:4.4.36-3+
      cd - # Back to /builds/$USER/mariadb-server/debian/output
      find /lib/*/libcrypt.* -ls # Show that new libcrypt is there
      apt-get -q --yes --fix-broken install
    fi
  - apt-get -q install apt || export SECOND_APT_STATUS="failed"
  # Upgrades from Bullseye or older to Trixie or newer always fail on:
  #   Preparing to unpack .../base-files_13.4_amd64.deb ...
  #   ******************************************************************************
  #   *
  #   * The base-files package cannot be installed because
  #   * /bin is a directory, but should be a symbolic link.
  #   *
  #   * Please install the usrmerge package to convert this system to merged-/usr.
  #   *
  #   * For more information please read https://wiki.debian.org/UsrMerge.
  #   *
  #   ******************************************************************************
  # Therefore, run this older base-files must be used:
  - |
    if [ "$SECOND_APT_STATUS" = "failed" ]
    then
      curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/b/base-files/base-files_13.2_amd64.deb
      apt-get -q install --no-install-recommends --yes ./base-files_13.2_amd64.deb
      # Ensure upgrades past 13.2 are blocked so tests don't fail on usrmerge issues
      apt-mark hold base-files
    fi
  # Complete upgrade of minimal stack
  - apt-get install -q --yes apt

.test-enable-plain-sid-repos: &test-enable-plain-sid-repos
  - apt-get install -qq --yes --no-install-recommends ca-certificates curl
  - curl -sLO https://snapshot.debian.org/archive/debian/20240531T083821Z/pool/main/b/base-files/base-files_13.2_amd64.deb
  # Replace any old repos with just Sid
  - echo 'deb http://deb.debian.org/debian sid main' > /etc/apt/sources.list
  # Upgrade minimal stack first
  - apt-get update -q
  - apt-get -q install --no-install-recommends --yes ./*.deb


upgrade from bookworm:
  stage: test
  image: debian:bookworm
  script:
    - *test-prepare-container
    - apt-get install -y entr
    - *test-enable-sid-repos
    - apt-get install -y entr

upgrade from bullseye:
  stage: test
  image: debian:bullseye
  script:
    - *test-prepare-container
    - apt-get install -y entr
    - *test-enable-sid-repos
    - apt-get install -y entr

upgrade from buster:
  stage: test
  image: debian:buster
  script:
    - *test-prepare-container
    - apt-get install -y entr
    - *test-enable-sid-repos
    - apt-get install -y entr

upgrade from stretch:
  stage: test
  image: debian:stretch
  script:
    - |
      cat > /etc/apt/sources.list <<EOF
      deb http://archive.debian.org/debian stretch main
      deb http://archive.debian.org/debian-security stretch/updates main
      EOF
    - *test-prepare-container
    - apt-get install -y entr
    - *test-enable-sid-repos
    - apt-get install -y entr

upgrade from jessie:
  stage: test
  image: debian:jessie
  script:
    - |
      cat > /etc/apt/sources.list <<EOF
      deb http://archive.debian.org/debian jessie main
      deb http://archive.debian.org/debian-security jessie/updates main
      EOF
    - *test-prepare-container
    - apt-get install -y --force-yes entr
    - *test-enable-sid-repos
    - apt-get install -y entr


plain upgrade from bookworm:
  stage: test
  image: debian:bookworm
  script:
    - *test-prepare-container
    - apt-get install -y entr
    - *test-enable-plain-sid-repos
    - apt-get install -y entr

plain upgrade from bullseye:
  stage: test
  image: debian:bullseye
  script:
    - *test-prepare-container
    - apt-get install -y entr
    - *test-enable-plain-sid-repos
    - apt-get install -y entr

plain upgrade from buster:
  stage: test
  image: debian:buster
  script:
    - *test-prepare-container
    - apt-get install -y entr
    - *test-enable-plain-sid-repos
    - apt-get install -y entr

plain upgrade from stretch:
  stage: test
  image: debian:stretch
  script:
    - |
      cat > /etc/apt/sources.list <<EOF
      deb http://archive.debian.org/debian stretch main
      deb http://archive.debian.org/debian-security stretch/updates main
      EOF
    - *test-prepare-container
    - apt-get install -y entr
    - *test-enable-plain-sid-repos
    - apt-get install -y entr

plain upgrade from jessie:
  stage: test
  image: debian:jessie
  script:
    - |
      cat > /etc/apt/sources.list <<EOF
      deb http://archive.debian.org/debian jessie main
      deb http://archive.debian.org/debian-security jessie/updates main
      EOF
    - *test-prepare-container
    - apt-get install -y --force-yes entr
    - *test-enable-plain-sid-repos
    - apt-get install -y entr
